const EXTRA_DAY_PRICE = 15;
const BASE_PRICE_BEFORE_15_DAYS = 10;
const BASE_PRICE_AFTER_15_DAYS = 12;
const DAYS_NORMAL_BIKE = 3;
const DAYS_VINTAGE_BIKE = 5;

export {
  EXTRA_DAY_PRICE,
  BASE_PRICE_BEFORE_15_DAYS,
  BASE_PRICE_AFTER_15_DAYS,
  DAYS_NORMAL_BIKE,
  DAYS_VINTAGE_BIKE,
};
